name: ubuntu-build

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cmake -S . -B build && cd build && make -j32
    - name: test
      run: ./testscript/conformance.py
